trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'todo-app-frontend/**'
pool:
  name: Default

stages:
  - stage: BuildTestAndDeploy
    displayName: 'Build, Test, and Deploy Todo Frontend'
    jobs:
      - job: BuildTestAndDeployJob
        displayName: 'Build, Test, and Deploy Job'
        steps:
          - checkout: self


          - task: Bash@3
            displayName: 'Build and test Docker image'
            inputs:
              targetType: 'inline'
              script: |
                
                cd $(Build.SourcesDirectory)/todo-app-frontend/

                docker build -t todo_app_frontend:latest .
                docker run --name todo_app_frontend -d -p 3000:3000 todo_app_frontend

                sleep 10
         
                bash check-response.sh
                docker stop todo_app_frontend

          - task: Docker@2
            displayName: 'Push Docker image'
            inputs:
              dockerRegistryEndpoint: 'DockerHub'
              containerRegistry: 'DockerHub'
              repository: 'todo_app_frontend'
              command: 'push'
              Dockerfile: '$(Build.SourcesDirectory)/todo-app-backend/Dockerfile'
              tags: 'latest'

          - task: Bash@3
            displayName: 'Deploy Docker Image to Render'
            inputs:
              targetType: 'inline'
              script: |
                curl $(DEPLOY_URL)
              


