trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'todo-app-backend/**'
pool:
  name: Default

stages:
  - stage: BuildTestAndDeploy
    displayName: 'Build, Test, and Deploy Todo Backend'
    jobs:
      - job: BuildTestAndDeployJob
        displayName: 'Build, Test, and Deploy Job'
        steps:
          - checkout: self

          - task: Bash@3
            displayName: 'Build and test Docker image'
            inputs:
              targetType: 'inline'
              script: |
                cd $(Build.SourcesDirectory)/todo-app-backend/

                docker build -t todo_app:latest .
                docker run --name todo_app -e ALLOWED_ORIGIN=http://localhost:3000 -d -p 5000:5000 todo_app:latest
                
                sleep 10
    
                bash check-response.sh || exit 1

                docker stop todo_app

          - task: Docker@2
            displayName: 'Push Docker image'
            inputs:
              containerRegistry: 'DockerHub'
              repository: 'dockerwave21/todo_app'
              command: 'push'
              Dockerfile: '$(Build.SourcesDirectory)/todo-app-backend/Dockerfile'
              tags: 'latest'
              containerRegistryType: 'Container Registry'
              dockerRegistryEndpoint: 'DockerHub'
              # arguments: '--build-arg DOCKERHUB_TOKEN=$(DOCKERHUB_TOKEN)'

          - task: Bash@3
            displayName: 'Deploy Docker Image to Render'
            inputs:
              targetType: 'inline'
              script: |
                curl $(DEPLOY_URL)
              


