trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'todo-app-frontend/**'
pool:
  name: Default

stages:
  - stage: BuildTestAndDeploy
    displayName: 'Build, Test, and Deploy Todo Frontend'
    jobs:
      - job: BuildTestAndDeployJob
        displayName: 'Build, Test, and Deploy Job'
        steps:
          - checkout: self

          - task: Docker@2
            displayName: 'Build and test Docker image'
            inputs:
              containerRegistry: 'DockerHub'
              repository: 'todo_app_frontend'
              command: 'build'
              Dockerfile: '$(Build.SourcesDirectory)/todo-app-frontend/Dockerfile'

          - task: Bash@3
            displayName: 'Run check-response.sh'
            inputs:
              targetType: 'inline'
              script: |
                cd $(Build.SourcesDirectory)/todo-app-frontend/
                bash check-response.sh

          - task: Docker@2
            displayName: 'Push Docker image'
            inputs:
              containerRegistry: 'DockerHub'
              repository: 'todo_app_frontend'
              command: 'push'
              Dockerfile: '$(Build.SourcesDirectory)/todo-app-backend/Dockerfile'
              tags: 'latest'

          - task: Bash@3
            displayName: 'Deploy Docker Image to Render'
            script: |
              curl $(DEPLOY_URL)
              


