trigger:
  branches:
    include:
      - main

variables:
  imageName: 'your-docker-hub-username/todo-app'
  imageVersion: $(version) 
  DOCKERHUB_PASSWORD: $(DOCKERHUB_PASSWORD)

jobs:
# - job: BuildAndTest
#   displayName: 'Build and Test'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - script: |
#       # Install dependencies
#       pip install -r requirements.txt

#       # Run tests
#       pytest tests/
#     displayName: 'Run Tests'

- job: PublishDockerImage
  displayName: 'Publish Docker Image'
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - task: Docker@2
    displayName: 'Build and Push'
    inputs:
      command: 'buildAndPush'
      containerRegistry: 'DockerHub'
      repository: '$(imageName)'
      tags: '$(imageVersion)'
      containerRegistryPassword: $(DOCKERHUB_PASSWORD)
