trigger:
  branches:
    include:
      - main

variables:
  imageName: 'dockerwave21/todo_app'
  imageVersion: $(version) 
  DOCKERHUB_TOKEN: $(DOCKERHUB_TOKEN)

jobs:
# - job: BuildAndTest
#   displayName: 'Build and Test'
#   pool:
#     vmImage: 'ubuntu-latest'
#   steps:
#   - script: |
#       # Install dependencies
#       pip install -r requirements.txt

#       # Run tests
#       pytest tests/
#     displayName: 'Run Tests'

- job: PublishDockerImage
  displayName: 'Publish Docker Image'
  steps:
  - task: Docker@2
    displayName: 'Build and Push'
    inputs:
      command: 'buildAndPush'
      containerRegistry: 'DockerHub'
      repository: '$(imageName)'
      tags: '$(imageVersion)'
      containerRegistryType: 'Container Registry'
      dockerRegistryEndpoint: 'DockerHub'
      arguments: '--build-arg DOCKERHUB_TOKEN=$(DOCKERHUB_TOKEN)'

