name: Create Release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: '!todo-app-frontend'
          
      - name: Build project 
        run: |
          zip -r todo-app-backend.zip todo-app-backend
          
          
      - name: Get Commit SHA
        id: commit_sha
        run: echo "::set-output name=sha::$(git rev-parse --short=7 HEAD)"
        

      - name: Create Tag
        run: |
          git tag -a v1.0.0 -m "Version 1.0.0"
          git push --tags
#       - name: Create Release
#         id: create_release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
#         with:
#           tag_name: ${{ steps.commit_sha.outputs.sha }}
#           release_name: Release ${{ steps.commit_sha.outputs.sha }}
#           draft: false
#           prerelease: false
#       - name: Upload Release Asset
#         id: upload-release-asset 
#         uses: actions/upload-release-asset@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.TOKEN }}
#         with:
#           upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
#           asset_path: ./todo-app-backend.zip
#           asset_name: todo-app-backend.zip
#           asset_content_type: application/zip
